stages:
  - build
  - test
  - package

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  image: gradle:jdk19
  script:
    - cd TourGuide
    - gradle build

test:
  stage: test
  image: gradle:jdk19
  script:
    - cd TourGuide
    - gradle test

package:
  stage: package
  image: gradle:jdk19
  script:
    - cd TourGuide
    - gradle jar
  artifacts:
    paths:
      - TourGuide/build/libs/*.jar
 